db prisma configuration
CHI-internship/KraudDonate-Service pull request #1
Opened 2022-10-28 12:37 UTC by TanyaDovzhenko

2022-10-30 15:03 UTC, lerik1408 commented on Dockerfile
> +RUN npx prisma generate
Strange file =) Because you tried to create a container for the app. You can connect with @pavlokolodka. He has the correct way.

Main idea. Use the docker file ONLY for deploying the database locally.

2022-10-30 15:05 UTC, lerik1408 commented on docker-compose.yml
> +  pgadmin-data:
Get rid of docker-compose

2022-10-30 15:07 UTC, lerik1408 reviewed
Good job anyway. Overcomplicated realization =)

2022-10-31 08:43 UTC, lerik1408 commented on Dockerfile
> +ENV POSTGRES_DB main
set PGDATA

2022-10-31 08:43 UTC, lerik1408 commented on package.json
> +    "start": "docker run -d --name postgresdb_main -p 6532:5432 -e PGDATA=/var/lib/postgresql/data/pgdata --rm postgresdb_main && nest start",
remove -e flag

2022-10-31 08:43 UTC, lerik1408 commented on package.json
> +    "start:dev": "docker run -d --name postgresdb_main -p 6532:5432 -e PGDATA=/var/lib/postgresql/data/pgdata --rm postgresdb_main && nest start --watch",
remove -e flag

2022-10-31 09:43 UTC, RamboUA requested changes

2022-10-31 09:43 UTC, RamboUA commented on prisma/schema.prisma
> +  id   Int     @id @default(autoincrement())
Is everything ok with indents in this file?

2022-10-31 09:50 UTC, RamboUA approved these changes

2022-10-31 10:00 UTC, merged